---
title: "Assignment7_607"
author: "Alvaro Bueno"
date: "10/13/2017"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
library(RCurl)
library(XML)
library(jsonlite)
library(knitr)

```


```{r html_table}
html <- url('https://raw.githubusercontent.com/delagroove/dataScience/master/books.html')
webpage <- readLines(html)
htmltable <- readHTMLTable(webpage)
htmldata <- htmlParse(webpage, encoding="UTF-8")
result_href <- xpathSApply(htmldata, "//*/table/tr/td/a", xmlGetAttr, 'href')
htmltable <- as.data.frame(htmltable)
htmltable$sourceUrl <- result_href
```


```{r xml_table}
xData <- getURL('https://raw.githubusercontent.com/delagroove/dataScience/master/books.xml')
doc <- xmlParse(xData)

xmltable <- xmlToDataFrame(
  getNodeSet(doc, "//book")
)
result_href <- xpathSApply(doc, "//*/book/Source", xmlGetAttr, 'url')
xmltable$sourceUrl <- result_href
```

```{r json_table}
jData <- getURL('https://raw.githubusercontent.com/delagroove/dataScience/master/books.json')
jsontable <- fromJSON(jData)
```

The tables are not exactly identical, but they can be if we rename the columns in the HTML table.

```{r rename_cols}
names(htmltable) <- c('Name','Author', 'Description','Published Date', 'Editorial', 'Format', 'NumPages', 'Source','SourceUrl')

kable(htmltable)
kable(xmltable)
kable(jsontable)

```